---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
'At length I realize,' he said,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
My sorrow, when she’s here with me,  
     Thinks these dark days of autumn rain  
Are beautiful as days can be;  
She loves the bare, the withered tree;  
     She walks the sodden pasture lane.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,    
      "To come and spoil the fun."  
        
## Last Verse  
<!--Put a short poem of your choice 8-20 lines,here!-->
Mother, the folk who live up in the clouds call out to me-  
 "We play from the time we wake till the day ends.  
 We play with the golden dawn, we play with the silver moon."  
 I ask, "But how am I to get up to you ?"  
 They answer, "Come to the edge of the earth, lift up your  
hands to the sky, and you will be taken up into the clouds."  
 "My mother is waiting for me at home, "I say, "How can I leave  
her and come?"  
 Then they smile and float away.  